# Generated by Django 5.2.5 on 2026-05-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_client_id_alter_detallepedido_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido_id',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app1.pedido'),
            preserve_default=False,
        ),
    ]
